### ISSUE TITLE
[Minor]: Test explorer test detection issue

### ISSUE THREAD

**Issue by kenenisa** [Julien-R44/japa-vscode#9]
Test name declaration using single quotes works but using backticks causes failure of detection for all proceeding tests.
![image](https://github.com/Julien-R44/japa-vscode/assets/53818162/b2d199c9-3314-4099-8bca-f882df5ed955)
![image](https://github.com/Julien-R44/japa-vscode/assets/53818162/ef6894dd-4a41-40bb-a1d4-08adc458ebd8)

**Comment by Julien-R44** [comment]
Yeah, in fact since you're using backticks, it's impossible for the extension to know the name of the test. Let's imagine you are using interpolations in your backticks :

```ts
test(`${myVariable}`, ({ assert }) => {

})
```

 then via AST, it's impossible to know what's the correct name

I don't think we'll support the possibility of launching tests that don't have fixed names via the extension
